---
swagger: "2.0"
info:
  description: "GoKabam API , access to all the GoKabam Services\n\nThis API will\
    \ cover all functionality for the company, including private management, administration\
    \ and finances\n"
  version: "1.0.0"
  title: "GoKabam API"
  contact:
    email: "willwoodlief@gokabam.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/willwoodlief/gokabam.alpha/1.0.0"
tags:
- name: "users"
  description: "Operations/information about regular users"
- name: "me"
  description: "An operation just effecting the logged in user"
- name: "companies"
  description: "Company Info, Settings and Finances. Some company info is public"
- name: "sellers"
  description: "Salesmen and selling activities. Includes customer relations for customers.\
    \ Includes sales flow"
- name: "self"
  description: "an operation which gets information only for the account that this\
    \ call has credentials for, includes private and public information"
- name: "public"
  description: "Information which anyone can see. If it does not have this tag, then\
    \ it requires credentials to see"
- name: "customer_services"
  description: "Controls Regular Users,Salesmen and Companies. Can change any setting\
    \ for regular accounts"
- name: "higher_admins"
  description: "Controls privileged Accounts (for example this company is also a regular\
    \ company in the api but private info and settings can only be accessed using\
    \ a higher_admin privilege)"
- name: "root"
  description: "Ultimate authority. Controls who is on the higher admin list. API\
    \ settings in general controlled from here"
schemes:
- "https"
consumes:
- "application/json"
- "application/x-yaml"
- "application/xml"
produces:
- "application/json"
- "application/x-yaml"
- "application/xml"
security:
- OauthSecurity: []
paths:
  /me:
    get:
      tags:
      - "users"
      - "me"
      summary: "Gets Informaton about my account"
      description: "returns all information about this > including private , protected,\
        \ and public."
      operationId: "readMe"
      parameters:
      - name: "User-Agent"
        in: "header"
        description: "All API consumers MUST provide a user agent"
        required: true
        type: "string"
      - name: "pageSize"
        in: "query"
        description: "Number of persons returned"
        required: false
        type: "integer"
        default: 20
        maximum: 100
        exclusiveMaximum: false
        minimum: 0
        exclusiveMinimum: true
        multipleOf: 10
        format: "int32"
      - name: "pageNumber"
        in: "query"
        description: "Page number"
        required: false
        type: "integer"
        default: 1
      responses:
        200:
          description: "Get My Information"
          schema:
            $ref: "#/definitions/AllReadableUserInfo"
          headers:
            X-Rate-Limit-Remaining:
              type: "integer"
              description: "How many calls consumer can do"
            X-Rate-Limit-Reset:
              type: "string"
              format: "date-time"
              description: "When rate limit will be reset"
        500:
          description: "An unexpected error occured."
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Rate-Limit-Remaining:
              type: "integer"
              description: "How many calls consumer can do"
            X-Rate-Limit-Reset:
              type: "string"
              format: "date-time"
              description: "When rate limit will be reset"
        default:
          description: "A totally unexpected response"
          headers:
            X-Rate-Limit-Remaining:
              type: "integer"
              description: "How many calls consumer can do"
            X-Rate-Limit-Reset:
              type: "string"
              format: "date-time"
              description: "When rate limit will be reset"
      security:
      - OauthSecurity:
        - "read:me"
    post:
      tags:
      - "users"
      - "me"
      summary: "Updates Information about my account"
      description: "Can update all basic user information about this account, includes\
        \ public , private and protected"
      operationId: "writeMe"
      parameters:
      - name: "User-Agent"
        in: "header"
        description: "All API consumers MUST provide a user agent"
        required: true
        type: "string"
      - in: "body"
        name: "userInfo"
        description: "Data the user can update"
        required: true
        schema:
          $ref: "#/definitions/AllWritableUserInfo"
      responses:
        204:
          description: "User Updated."
          headers:
            X-Rate-Limit-Remaining:
              type: "integer"
              description: "How many calls consumer can do"
            X-Rate-Limit-Reset:
              type: "string"
              format: "date-time"
              description: "When rate limit will be reset"
        400:
          description: "User could not be updated."
          headers:
            X-Rate-Limit-Remaining:
              type: "integer"
              description: "How many calls consumer can do"
            X-Rate-Limit-Reset:
              type: "string"
              format: "date-time"
              description: "When rate limit will be reset"
        500:
          description: "An unexpected error occured."
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Rate-Limit-Remaining:
              type: "integer"
              description: "How many calls consumer can do"
            X-Rate-Limit-Reset:
              type: "string"
              format: "date-time"
              description: "When rate limit will be reset"
        default:
          description: "A totally unexpected response"
          headers:
            X-Rate-Limit-Remaining:
              type: "integer"
              description: "How many calls consumer can do"
            X-Rate-Limit-Reset:
              type: "string"
              format: "date-time"
              description: "When rate limit will be reset"
securityDefinitions:
  OauthSecurity:
    description: "Oauth security system. All operations are used with it"
    type: "oauth2"
    authorizationUrl: "https://oauth.simple.api/oauth/authorize"
    tokenUrl: "https://oauth.simple.api/oauth/token"
    flow: "accessCode"
    scopes:
      write:user: "write user information that is not your user"
      read:user: "read user information that is not yours"
      read:me: "read my information, all users are automatically granted this"
      write:me: "write my information, all users are automatically granted this"
definitions:
  AllReadableUserInfo:
    allOf:
    - $ref: "#/definitions/UserPublicInfo"
    - $ref: "#/definitions/UserProtectedInfo"
    - $ref: "#/definitions/UserPrivateInfo"
  AllWritableUserInfo:
    allOf:
    - $ref: "#/definitions/UserPublicInfo"
    - $ref: "#/definitions/UserProtectedInfo"
    - $ref: "#/definitions/UserPrivateInfo"
    - $ref: "#/definitions/UserPassword"
  UserPassword:
    properties:
      password:
        type: "string"
        example: "bats?No!1235"
        description: "The password lets users login to the api service as well as\
          \ web services supported by this api"
        minLength: 8
        maxLength: 16
        pattern: "[a-zA-Z0-9!@#\\$%\\^&\\*\\?]{8,16}"
    title: "A User Password"
    description: "This password is writable only , and can only be set"
  UserPrivateInfo:
    properties:
      notes:
        type: "string"
        description: "A list of thoughts and notes"
    title: "Private User Information"
    description: "Only the user or authorized people will ever see this"
  UserProtectedInfo:
    properties:
      friendList:
        type: "string"
        description: "A list of friend information, right how just a string will be\
          \ an array later"
    title: "Protected UserInformation"
    description: "Friends have access to this information"
  UserPublicInfo:
    required:
    - "username"
    properties:
      firstName:
        type: "string"
        example: "John"
        description: "first name"
      lastName:
        type: "string"
        example: "Doe"
        description: "last name"
      username:
        type: "string"
        example: "john1doe6"
        description: "Username used to connect to the service"
        minLength: 8
        maxLength: 64
        pattern: "[a-z0-9]{8,64}"
      lastTimeOnline:
        type: "string"
        format: "date-time"
        example: "2016-06-10T12:36:58.014Z"
        description: "The last time this person was connected to the service as a"
        readOnly: true
    title: "Public User Information"
    description: "Anyone can see this information at all times"
  ErrorMessage:
    required:
    - "longMessage"
    - "shortMessage"
    properties:
      longMessage:
        type: "string"
        description: "A long error description"
      shortMessage:
        type: "string"
        description: "A short error description"
    title: "MultiDeviceErrorMessage"
    description: "An error message with a long and a short description"
  MultilingualErrorMessage:
    type: "object"
    properties:
      defaultLanguage:
        $ref: "#/definitions/ErrorMessage"
    title: "MultiLingualMultiDeviceErrorMessage"
    description: "An multilingual error message (hashmap) with a long and a short\
      \ description"
    example:
      defaultLanguage:
        longMessage: "We're deeply sorry but an error occured"
        shortMessage: "Error"
      fr:
        longMessage: "Nous sommes désolé mais une erreur est survenu"
        shortMessage: "Erreur"
    additionalProperties:
      $ref: "#/definitions/ErrorMessage"
  Error:
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "string"
        example: "UNERR"
        description: "# Error Enum Definitions\n\n  | Name | Definition |\n  | -------\
          \ | -------- |\n  | DBERR   | A database error occured    |\n  | DBERR \
          \  | A database error occured    | \nsome texts\nText attributes _italic_,\
          \ *italic*, __bold__, **bold**, `monospace`.                     \nHorizontal\
          \ rule \n\n  ---\n\n  Bullet list \n\n    * apples\n    * oranges\n    *\
          \ pears\n\n  Numbered list\n\n    1. apples\n    2. oranges\n    3. pears\n\
          \n  A [link](http://example.com).\n\n  \n"
        enum:
        - "DBERR"
        - "NTERR"
        - "UNERR"
      message:
        $ref: "#/definitions/MultilingualErrorMessage"
    title: "MultiLingualMultiDeviceError"
    description: "Give full information about the problem"
parameters:
  pageSize:
    name: "pageSize"
    in: "query"
    description: "Number of persons returned"
    required: false
    type: "integer"
    default: 20
    maximum: 100
    exclusiveMaximum: false
    minimum: 0
    exclusiveMinimum: true
    multipleOf: 10
    format: "int32"
  pageNumber:
    name: "pageNumber"
    in: "query"
    description: "Page number"
    required: false
    type: "integer"
    default: 1
  userAgent:
    name: "User-Agent"
    in: "header"
    description: "All API consumers MUST provide a user agent"
    required: true
    type: "string"
responses:
  Standard500ErrorResponse:
    description: "An unexpected error occured."
    schema:
      $ref: "#/definitions/Error"
    headers:
      X-Rate-Limit-Remaining:
        type: "integer"
        description: "How many calls consumer can do"
      X-Rate-Limit-Reset:
        type: "string"
        format: "date-time"
        description: "When rate limit will be reset"
  PersonDoesNotExistResponse:
    description: "Person does not exist."
    headers:
      X-Rate-Limit-Remaining:
        type: "integer"
        description: "How many calls consumer can do"
      X-Rate-Limit-Reset:
        type: "string"
        format: "date-time"
        description: "When rate limit will be reset"
  TotallyUnexpectedResponse:
    description: "A totally unexpected response"
    headers:
      X-Rate-Limit-Remaining:
        type: "integer"
        description: "How many calls consumer can do"
      X-Rate-Limit-Reset:
        type: "string"
        format: "date-time"
        description: "When rate limit will be reset"
